% UM-SJTU JI PHYS1600J Project Template based on RevTeX 4.2 Template.
\documentclass[reprint]{revtex4-2}

% You can add packages here.
\usepackage{lipsum}
\usepackage{graphicx}
\usepackage{geometry}
\usepackage{subfigure}
\usepackage{amsfonts,amsmath,amssymb}
\usepackage{enumerate}
\usepackage{dcolumn}
\usepackage{bm}
\usepackage[colorlinks,citecolor=black,urlcolor=black]{hyperref}
\hypersetup{colorlinks=true,linkcolor=black}
\usepackage[mathlines]{lineno}

% Additional Packages
\usepackage{float}  % Float